### ISSUE TITLE
Terminal and Sidebar background colour

### ISSUE THREAD

**Issue by onetrev** [liviuschera/noctis#1]
I noticed that Noctis and Noctis Sereno have slightly different colour / tone to the background in the terminal and sidebar area, whereas Noctis Azureus and Obscuro don't. Just wondering if this could be changed so that those two variants have slightly different backgrounds to those areas too?

**Comment by liviuschera** [comment]
Hey Trevor thanks for your feedback. The different color lightness was initially implemented so that the theme would suit different tastes. Lately I found myself using Noctis Azureus as my main theme and I realized that I actually liked it better to have a visual separation of the terminal and sidebar of the original Noctis. So I'm thinking of giving this a go.

**Comment by liviuschera** [comment]
Done. I'd appreciate if you would give it a go and leave a feedback.

**Comment by onetrev** [comment]
Awesome! I tried it and it's perfect! I especially like the terminal colour for Azureus. Actually, could be cool if one day you add an additional variant where the editor bg is swapped with terminal bg, kind of like how Noctis and Noctis Sereno are. But I'm get getting greedy. :)

BTW, I didn't mention it before. but technically Noctis Lux terminal area background could use a slight contrast too if we are keeping everything consistent. But whatever. I think this can be closed. Thanks again!

**Comment by liviuschera** [comment]
You are right about Noctis Lux. I'll get on to it. In regards to a new variant I would leave it as it is for now. In future I might add another variant with a new background color altogether.
